<?php

namespace LWV\ToolkitBundle\Entity\Toolkit;

use Doctrine\ORM\EntityRepository;

/**
 * ToolkitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolkitRepository extends EntityRepository
{
}