_user:
    resource: "@LWVToolkitBundle/Resources/config/User/routing.yml"

_frontend:
    resource: "@LWVToolkitBundle/Resources/config/Frontend/routing.yml"
    pattern: /

_staff:
    resource: "@LWVToolkitBundle/Resources/config/Staff/routing.yml"

hello_world:
    pattern:  /hello/{name}
    defaults: { _controller: LWVToolkitBundle:Default:index }