_user:
    resource: "@LWVToolkitBundle/Resources/config/User/routing.yml"

_shop:
    resource: "@LWVToolkitBundle/Resources/config/Shop/routing.yml"

_staff:
    resource: "@LWVToolkitBundle/Resources/config/Staff/routing.yml"

hello_world:
    pattern:  /hello/{name}
    defaults: { _controller: LWVToolkitBundle:Default:index }