parameters:
    lwv_toolkit_listener_user.login_listener.class: LWV\ToolkitBundle\Listener\User\LoginListener

services:
    lwv_toolkit_listener_user.login_listener:
        class: %lwv_toolkit_listener_user.login_listener.class%
        arguments: [ @session ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }