parameters:
#    lwv_toolkit.example.class: LWV\ToolkitBundle\Example

services:
#    lwv_toolkit.example:
#        class: %lwv_toolkit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
