LWV\ToolkitBundle\Entity\User\User:
    properties:
        username:
            - NotBlank:
                groups: profile
                message: Username cannot be left blank.
        email:
            - NotBlank:
                groups: profile
                message: Email cannot be left blank
            - Email:
                groups: profile
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        password:
            - MaxLength: { limit: 20, message: "Your password must not exceed {{ limit }} characters." }
            - MinLength: { limit: 4, message: "Your password must have at least {{ limit }} characters." }
            - NotBlank: ~
LWV\ToolkitBundle\Entity\User\Profile:
    properties:
        name:
            - NotBlank: { groups: [profile] }
        pubName:
            - NotBlank: { groups: [profile] }
LWV\ToolkitBundle\Entity\Toolkit\Toolkit:
    properties:
        name:
            - NotBlank: ~
        url:
            - NotBlank: ~
        maintenance_message:
            - NotBlank: ~
LWV\ToolkitBundle\Entity\User\Company:
    properties:
        name:
            - NotBlank: ~
        account_no:
            - NotBlank: ~
        address1:
            - NotBlank: ~
        post_code:
            - NotBlank: ~
LWV\ToolkitBundle\Entity\Product\ProductCategory:
    properties:
        name:
            - NotBlank: ~
        slug:
            - NotBlank: ~
        description:
            - NotBlank: ~