<?php
namespace LWV\ToolkitBundle\Entity\Category;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CategoryRepository extends NestedTreeRepository
{
    // FINISH THIS!
    public function getAllCategoriesBySegment()
    {
        $dql = 'SELECT c FROM LWV\ToolkitBundle\Entity\Category\Category c ' .
               'ORDER BY c.name ASC';

        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }
}