<?php
namespace LWV\ToolkitBundle\Entity\Product;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProductCategoryRepository extends EntityRepository
{
    // FINISH THIS!
    /*public function getAllCategoriesBySegment()
    {
        $dql = 'SELECT c FROM LWV\ToolkitBundle\Entity\Product\ProductCategory c ' .
               'ORDER BY c.name ASC';

        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }*/
    
    public function getIndentedName()
    {
        return str_repeat("  ", $this->lvl).$this->name;
    }
}