<?php

namespace LWV\ToolkitBundle\Entity\Staff\Order;

use Doctrine\ORM\EntityRepository;

/**
 * FrontendOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
}