<?php
namespace LWV\ToolkitBundle\Entity\Frontend;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /*
    public function getActiveProductsFromCategorySlug($slug)
    {
        $dql = 'SELECT p, i FROM LWV\ToolkitBundle\Entity\Frontend\Product p ' .
               'LEFT JOIN p.images i ' .
               'LEFT JOIN p.category c ' .
               'WHERE c.slug = :slug ' .
               'AND p.visible = 1 ' .
               'ORDER BY p.name ASC';

        $query = $this->getEntityManager()->createQuery($dql)->setParameter('slug', $slug);;

        return $query->getResult();
    }
    */
    
    public function getActiveProductsWithImages()
    {
        $dql = 'SELECT p, i FROM LWV\ToolkitBundle\Entity\Frontend\Product p ' .
               'LEFT JOIN p.images i ' .
               'WHERE p.visible = 1 ' .
               'ORDER BY p.name ASC';

        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }
}