login:
    pattern:  /login
    defaults: { _controller: LWVToolkitBundle:User\Login:login }
    
login_check:
    pattern: /login_check

logout:
    pattern: /logout
    
#staff_login:
#    pattern: /staff/login
#    defaults: { _controller: LWVToolkitBundle:User\Login:staffLogin }

#staff_login_check:
#    pattern: /staff/login_check
    
#staff_logout:
#    pattern: /staff/logout

tk_profile:
    pattern: /myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }

tk_update_profile:
    pattern: /myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }
    requirements:
        _method: POST

tk_password:
    pattern: /myaccount/password
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:password }

tk_update_password:
    pattern: /myaccount/password
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:password }
    requirements:
        _method: POST
        
staff_profile:
    pattern: /staff/myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }


staff_update_profile:
    pattern: /staff/myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }
    requirements:
        _method: POST

password_request_update:
    pattern: /request/password
    defaults: { _controller: LWVToolkitBundle:User\Reset:passwordRequest }
    requirements:
        _method: POST
        
password_request:
    pattern: /request/password
    defaults: { _controller: LWVToolkitBundle:User\Reset:passwordRequest }
    
password_reset_update:
    pattern: /reset/password/{key}
    defaults: { _controller: LWVToolkitBundle:User\Reset:passwordReset }
    requirements:
        _method: POST
        
password_reset:
    pattern: /reset/password/{key}
    defaults: { _controller: LWVToolkitBundle:User\Reset:passwordReset }
    
password_reset_success:
    pattern: /reset/success
    defaults: { _controller: LWVToolkitBundle:User\Reset:passwordSuccess }
