login:
  pattern:  /login
  defaults: { _controller: LWVToolkitBundle:User\Login:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

tk_profile:
    pattern: /myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }

tk_update_profile:
    pattern: /myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }
    requirements:
        _method: POST

staff_profile:
    pattern: /staff/myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }


staff_update_profile:
    pattern: /staff/myaccount/profile
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:profile }
    requirements:
        _method: POST

password:
    pattern: /password
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:password }

update_password:
    pattern: /password
    defaults: { _controller: LWVToolkitBundle:User\Dashboard:password }
    requirements:
        _method: POST

