login:
    pattern:  /login
    defaults: { _controller: LWVToolkitBundle:User:Login:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

profile:
    pattern: /profile
    defaults: { _controller: LWVToolkitBundle:User:Dashboard:profile }

update_profile:
    pattern: /profile
    defaults: { _controller: LWVToolkitBundle:User:Dashboard:profile }
    requirements:
        _method: POST

password:
    pattern: /password
    defaults: { _controller: LWVToolkitBundle:User:Dashboard:password }

update_password:
    pattern: /password
    defaults: { _controller: LWVToolkitBundle:User:Dashboard:password }
    requirements:
        _method: POST

